In [ ]:
%%capture outputtext

# When in Colab:
!pip install langchain-community
!pip install langchain-ollama
!curl -fsSL https://ollama.com/install.sh | sh
!ollama serve &>/dev/null&

In [ ]:
# # !ollama pull llama3.1:8b
!ollama pull llama3.1

In [2]:
from langchain_ollama import ChatOllama
from IPython.display import display, Markdown, Latex

llm = ChatOllama(
    model = "llama3.1",
#    model = "llama3.1:8b",
    temperature = 0,
)

In [ ]:
# Local: 50 s
result = llm.invoke("Solve the equation: 2^(5x-1)=4^7")
display(Markdown(result.content))

A nice exponential equation!

Let's simplify both sides:

2^(5x-1) = (2^2)^7
= 2^(14)

Now we have:
2^(5x-1) = 2^(14)

Since the bases are equal, we can equate the exponents:
5x - 1 = 14

Add 1 to both sides:
5x = 15

Divide by 5:
x = 3

So, the solution is x = 3.

In [4]:
result.usage_metadata

{'input_tokens': 26, 'output_tokens': 107, 'total_tokens': 133}

{'input_tokens': 26, 'output_tokens': 107, 'total_tokens': 133}